### ISSUE TITLE
Adding a pkgdown site for browsing of docs

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/rOpenScPCA#16]
## Summary 

Looks like there's a good amount of stuff going on here so far! :tada: 
I'm a newb and just starting out testing out this package and what's here. So I am looking for some standard R package docs. 

## Proposed idea
Are there plans to add a pkgdown site for easy standardized browsing or should I look for docs elsewhere? Maybe the plan is to put them to the main `readthedocs.io` site? 

Wherever the R package specific docs will/do live can we add to the little "About" area of this github repo page and possibly to the README? 

## Resource
Here's a nice github action so this can all be done automagically 🪄 https://github.com/FanWangEcon/PkgTestR/blob/master/.github/workflows/pkgdown.yaml

I am happy to file this PR myself if you wanna go with `pkgdown` but just wanted to check what the plans were for this.

**Comment by cansavvy** [comment]
@allyhawkins It seems like you've been working on a lot of this so I'm just gonna start with tagging you. 😄

**Comment by sjspielman** [comment]
> I am happy to file this PR myself if you wanna go with pkgdown but just wanted to check what the plans were for this.

We don't have _a ton_ of plans for this at the moment, except for this which only focuses on the clustering functions: https://github.com/AlexsLemonade/OpenScPCA-analysis/issues/799. I do like `pkgdown`, but we might want to discuss more whether it's the right use case for this package. I'll add this to bring up in next sprint planning!

**Comment by sjspielman** [comment]
We have discussed this, and we prefer to keep docs and examples for this package housed as modules within the `OpenScPCA-analysis` repository, e.g.:

- `hello-remote`: https://github.com/AlexsLemonade/OpenScPCA-analysis/tree/main/analyses/hello-clusters
- `seurat-conversion`: https://github.com/AlexsLemonade/OpenScPCA-analysis/tree/main/analyses/seurat-conversion
